config/routes.rb
Rails.application.routes.draw do


  # these are the actions related to authentication
  get "_who_are_u" => "authenticate#who_are_u", as: 'who_are_u'
  post "_prove_it" => "authenticate#prove_it", as: 'prove_it'
  post "_about_urself" => "authenticate#about_urself", as: 'about_urself'
  get "_from_mail/(:user_token)" => "authenticate#from_mail", as: 'from_mail'
  post "_ur_secrets" => "authenticate#ur_secrets", as: "ur_secrets"
  get "_reset_mail" => "authenticate#reset_mail", as: 'reset_mail'
  get "_see_u" => "authenticate#see_u", as: 'see_u'
    
  # these should only be available to administrators...
  scope module: 'admin' do  
  
    # for authentication
    resources :users
    get 'users/:id/role_change/:role' => 'users#role_change', as: 'role_change'
    resources :user_actions
    resources :user_sessions  
    resources :site_maps
    
    # for administration
    resources :events
	resources :sources
	resources :source_refs
    resources :individuals
    get 'all_individuals_by_uid' => 'individuals#all_individuals_by_uid', as: 'all_individuals_by_uid'
    get 'individual_by_uid/:uid' => 'individuals#individual_by_uid', as: 'individual_by_uid'
    resources :unions
    get 'all_unions_by_uid' => 'unions#all_unions_by_uid', as: 'all_unions_by_uid'
    get 'union_by_uid/:uid' => 'unions#union_by_uid', as: 'union_by_uid'
           
  end    

  # resources for the app
  get 'surnames' => 'geni#surnames', as: 'surnames'  
  get 'names_for_surname' => 'geni#names_for_surname', as: 'names_for_surname'     
  get 'names_for_term' => 'geni#names_for_term', as: 'names_for_term' 
  get 'sources_for_term' => 'geni#sources_for_term', as: 'sources_for_term'   
  get 'depth_change/:change/(:uid)' => 'geni#depth_change', as: 'depth_change' 
  get 'toggle_edit/(:uid)' => 'geni#toggle_edit', as: 'toggle_edit' 
  get 'import' => 'geni#import', as: 'import'
  post 'file_upload' => 'geni#file_upload', as: 'file_upload'
  
  get 'edit/:uid' => 'geni#edit', as: 'edit'
  get 'detail/:uid' => 'geni#detail', as: 'detail'
  get 'clear' => 'geni#clear', as: 'clear'  
  get 'union_edit/:uuid/:uid' => 'geni#union_edit', as: 'union_edit'
  post 'save/:uid' => 'geni#save', as: 'save'  
  post 'union_save/:uid/:uuid' => 'geni#union_save', as: 'union_save'  
  
  get 'source_edit/(:sid)' => 'geni#source_edit', as: 'source_edit'
  get 'source_delete/:sid/:uid' => 'geni#source_delete', as: 'source_delete'  
  get 'source_content/:sid' => 'geni#source_content', as: 'source_content'  
  post 'source_save/:sid' => 'geni#source_save', as: 'source_save'    
  
=begin  
  match 'marriage_new/:uid' => 'geni#marriage_new', as: 'marriage_new', via: [:get, :post]
  post 'save_marriage_new/:uid' => 'geni#save_marriage_new', as: 'save_marriage_new'  
  match 'marriage_existing/:uid' => 'geni#marriage_existing', as: 'marriage_existing', via: [:get, :post]
  post 'save_marriage_existing/:uid' => 'geni#save_marriage_existing', as: 'save_marriage_existing'    
  get 'delete_marriage/:uid/:uuid' => 'geni#delete_marriage', as: 'delete_marriage' 
=end

  match 'add_spouse/:uid/:uuid' => 'geni#add_spouse', as: 'add_spouse', via: [:get, :post]  
  match 'new_spouse/:uid/:uuid' => 'geni#new_spouse', as: 'new_spouse', via: [:get, :post]    
  post 'save_added_spouse/:uid/:uuid' => 'geni#save_added_spouse', as: 'save_added_spouse'  
  post 'create_new_spouse/:uid/:uuid' => 'geni#create_new_spouse', as: 'create_new_spouse'   
  get 'remove_spouse/:uid/:uuid/:ruid' => 'geni#remove_spouse', as: 'remove_spouse'  
	
  match 'add_child/:uid/:uuid' => 'geni#add_child', as: 'add_child', via: [:get, :post]  
  match 'new_child/:uid/:uuid' => 'geni#new_child', as: 'new_child', via: [:get, :post]    
  post 'save_added_child/:uid/:uuid' => 'geni#save_added_child', as: 'save_added_child'  
  post 'create_new_child/:uid/:uuid' => 'geni#create_new_child', as: 'create_new_child'    
  get 'remove_child/:uid/:puid' => 'geni#remove_child', as: 'remove_child'  
  
  get 'new_person' => 'geni#new_person', as: 'new_person' 
  post 'create_person' => 'geni#create_person', as: 'create_person' 
  
  get 'remove_parent/:uid/:puid' => 'geni#remove_parent', as: 'remove_parent'
  match 'new_parent/:uid/:sex/(:uuid)' => 'geni#new_parent', as: 'new_parent', via: [:get, :post]    
  match 'create_new_parent/:uid/(:uuid)' => 'geni#create_new_parent', as: 'create_new_parent', via: [:get, :post]  
  
  match 'search' => 'geni#search', as: 'search', via: [:get, :post]
  post 'search_results' => 'geni#search_results', as: 'search_results'  
  
  get 'vis_change/(:uid)' => 'geni#vis_change', as: 'vis_change'
  
  get 'compare/:uid/(:uid1)' => 'geni#compare', as: 'compare'
  get 'link/:uid/:uid1/:link' => 'geni#link', as: 'link'  

  # this has to be the last one or else...
  get ':uid' => 'geni#display', as: 'display'

  root "geni#search", as: "root"
    
end

app/controllers/geni_controller.rb
class GeniController < ApplicationController

  
  ###################################################################################
  #
  # browse & search
  #    
  def surnames
    @surnames = Individual.surnames(params[:term])
  end  
  def names_for_surname
    @surname = params[:surname]
    is_user = @current_user and @current_user.user? 
    @names = Individual.names_for_surname( @surname, is_user )     
  end
  def names_for_term
	@term = params[:term]    	
	if @term.length > 1
	  is_user = @current_user and @current_user.user? 
      @names = Individual.names_for_term( @term, is_user ) 
	end
  end  
  def sources_for_term
	@term = params[:term]    	
	if @term.length > 1
	  is_user = @current_user and @current_user.user? 
      @sources = Source.titles_for_term( @term, is_user ) 
	end
  end  

  ###################################################################################
  #
  # display the tree (as HTML tree or javascript graphics)
  #   
  def display
    #  tree-font is where we start with the fonts
    #  min-tree-font is how far we go down... translates into
    #    tree-depth, one depth increment corresponds to 2 font increments
    #  absolute-min-tree-font is what you think it is
    init_session
	@level = 1
    @maxlevel = session[:'max-level']	
    @font = session[:'tree-font']
    @individual = Individual.by_uid( params[:uid] )     
	if !@individual
	  redirect_to root_path
	elsif session[:display] == "graph"
	  is_user = @current_user and @current_user.user?
	  is_editor = @current_user and @current_user.user?	  
	  @nodes = [] 
	  @edges = []  
	  @nodes << @individual.graph_focus_node( is_user, (is_editor and session[:edit] == 'on') )		  
	  @nodes, @edges = @individual.graph_up( 
	                     0, @maxlevel, @nodes, @edges, is_user, (is_editor and session[:edit] == 'on') )		           
	  @nodes, @edges = @individual.graph_down( 
	                     0, @maxlevel, @nodes, @edges, is_user, (is_editor and session[:edit] == 'on') )	         
	  render :graph	
	else
	  render
	end
  end  
  
  def detail
    @individual = Individual.by_uid( params[:uid] )
	@sources = @individual.sources  
  end
  
  def depth_change
    init_session
    session[:'max-level'] -= (params[:change].to_i )
    if session[:'max-level'] > session[:'absolute-max-level']
      session[:'max-level'] = session[:'absolute-max-level']
    elsif session[:'max-level'] < 1
      session[:'max-level'] = 1
    end	
    @individual = Individual.by_uid( params[:uid] )
    if @individual 
      redirect_to display_path( @individual.uid )
    else
      redirect_to root_path
    end
  end
  
  def toggle_edit
    if session[:edit] == 'on' 
      session[:edit] = 'off' 
    else
      session[:edit] = 'on'
    end
    @individual = Individual.by_uid( params[:uid] )
    if @individual 
      redirect_to display_path( @individual.uid )
    else
      redirect_to root_path
    end    
  end
  
  def vis_change
    init_session
    @individual = Individual.by_uid( params[:uid] )
    if session[:display] == "graph"
      session[:display] = "tree"
    else
      session[:display] = "graph"
    end
    if @individual 
      redirect_to display_path( @individual.uid )
    else
      redirect_to root_path
    end
  end
  
  ###################################################################################
  #
  # compare two trees
  #   
  def compare
    init_session
	@level = 1
    @maxlevel = session[:'max-level']	
    @font = session[:'tree-font']  
    @individual = Individual.by_uid( params[:uid] )
    @individual1 = Individual.by_uid( params[:uid1] )
	if !@individual
	  redirect_to root_path
	elsif !@individual1
	  @individual1 = @individual.other_tree_match
	  redirect_to root_path if ! @individual1
	end
  end
  def link
    @individual = Individual.by_uid( params[:uid] )
    @individual1 = Individual.by_uid( params[:uid1] )
    if !@individual or !@individual1 or
       @individual.tree == @individual1.tree
	  redirect_to root_path
	elsif params[:link] == "link"
      @individual.linkuid = params[:uid1]
      @individual.save
      @individual1.linkuid = params[:uid]
      @individual1.save      
	elsif params[:link] == "unlink"
      @individual.linkuid = nil
      @individual.save
      @individual1.linkuid = nil
      @individual1.save       
    end
    redirect_to :back
  end
    
  ###################################################################################
  #
  #  edit individual
  #   
  def edit
    @individual = Individual.by_uid( params[:uid] )
    @editable = params[:editable] == 'true' 
	@sources = @individual.sources
  end 
  def new_person
    @individual = Individual.new( name: "New Person" )
    @individual.save
	@sources = []
	@editable = true
  end  
  def save

    @individual = Individual.by_uid( params[:uid] )  
    @individual.surname = params[:surname]
    @individual.given = params[:given]
    @individual.nickname = params[:nickname]
    @individual.name = @individual.given + ' /' + @individual.surname + '/'
    @individual.prefix = params[:prefix]
    @individual.suffix = params[:suffix]
    @individual.sex = params[:sex]
    @individual.pedigree = params[:pedigree]
    @individual.note = params[:note]
    
    @individual.update_birth( rawdate: params[:Birthdate] ) 
    @individual.update_birth( location: params[:Birthlocation] ) 

    if params[:Deathdate].length > 0 or params[:Deathlocation].length > 0
      @individual.update_death( rawdate: params[:Deathdate] ) 
      @individual.update_death( location: params[:Deathlocation] )
    end 
    
    @individual.user_id = @current_user.id
    @individual.save

	@source = Source.where( id: params[:'sources-search-sid'] ).first 
	if @source
      sref = SourceRef.create( individual_uid: @individual.uid,
                               source_id: @source.id )
	  sref.save
	end
	
	redirect_back fallback_location: display_path( @individual.uid )
  end

  ###################################################################################
  #
  #  edit union
  #   
  def union_edit	  
    @individual = Individual.by_uid( params[:uid] )
	@union = Union.by_uid( params[:uuid] )
  end
  
  def union_save
	
    @individual = Individual.by_uid( params[:uid] )  
	@union = Union.by_uid( params[:uuid] )
    
    @union.update_marriage( rawdate: params[:Marriagedate] ) 
    @union.update_marriage( location: params[:Marriagelocation] ) 	
    @union.note = params[:note]
	
    if params[:Divorcedate].length > 0 or params[:Divorcelocation].length > 0
      @union.update_divorce( rawdate: params[:Divorcedate] ) 
      @union.update_divorce( location: params[:Divorcelocation] ) 	
    end 
	
    @union.user_id = @current_user.id
    @union.save

    redirect_back fallback_location: display_path( @individual.uid )
  end
      
  ###################################################################################
  #
  #  add child
  #   
  def add_child
    @union = Union.by_uid( params[:uuid] )
    @individual = Individual.by_uid( params[:uid] )   
    if !@union
      @union = Union.new
      if @individual.female?
        @union.wife_uid = @individual.uid
      else
	    @union.husband_uid = @individual.uid
	  end  
	  @union.save
    end 
  end
  def save_added_child
    @individual = Individual.by_uid( params[:uid] )
    @union = Union.by_uid( params[:uuid] )
    @child = Individual.by_uid( params[:'names-search-uid'] )    
    if @child
      @child.parents = @union
      @child.user_id = @current_user.id    
      @child.save
    end
    redirect_back fallback_location: display_path( @individual.uid )
  end
  
  def new_child
    @individual = Individual.by_uid( params[:uid] )
    @union = Union.by_uid( params[:uuid] )  
    @gender = params[ :gender ]
    if !@union
      @union = Union.new
      if @individual.female?
        @union.wife_uid = @individual.uid
      else
	    @union.husband_uid = @individual.uid
	  end  
	  @union.save
	end
  end    
  
  def create_new_child
    @individual = Individual.by_uid( params[:uid] )
    @union = Union.by_uid( params[:n_uuid] )
    @child = Individual.new( given: params[:given], surname: params[:surname], 
               sex: params[:sex], nickname: params[:nickname],
               prefix: params[:prefix], suffix: params[:suffix], 
			   pedigree: params[:pedigree] )
			   
    @child.name = @child.given + ' /' + @child.surname + '/'    
    @child.update_birth( rawdate: params[:Birthdate] ) 
    @child.update_birth( location: params[:Birthlocation] ) 
    @child.parents = @union
    @child.user_id = @current_user.id
    @child.tree = params[:tree]
    @child.save
    redirect_back fallback_location: display_path( @individual.uid )
  end
    
  def remove_child
    @child = Individual.by_uid( params[:uid] )
    @child.parents_uid = nil
    @child.save 
    @parent = Individual.by_uid( params[:puid] )
    redirect_back fallback_location: display_path( @parent.uid )
  end  
  
  ###################################################################################
  #
  #  add spouse
  #  

  # add existing spouse
  def add_spouse
    @union = Union.by_uid( params[:uuid] )
    @individual = Individual.by_uid( params[:uid] )   
    if !@union
      @union = Union.new
      if @individual.female?
        @union.wife_uid = @individual.uid
      else
	    @union.husband_uid = @individual.uid
	  end      	     
    end      
  end
  def save_added_spouse
    @individual = Individual.by_uid( params[:uid] )
    @spouse = Individual.by_uid( params[:'names-search-uid'] )    	
	@union = Union.by_uid( params[:uuid] )
	@union = Union.new if !@union
	if @individual.male?
	  @union.husband = @individual if !@union.husband
	  @union.wife = @spouse
	else
	  @union.wife = @individual if !@union.husband
	  @union.husband = @spouse	  
    end
    @union.update_marriage( rawdate: params[:Marriagedate] ) 
    @union.update_marriage( location: params[:Marriagelocation] )     
    @union.save

app/views/geni/_add_spouse.html.erb
<div class="panel panel-danger">
  <div class="panel-heading">
    <b>Add existing 
    (<%= link_to 'new', new_spouse_path( individual.uid, union.uid ), 
				        class: 'editlink', remote: true %>) 
    person as spouse for</b> <%= individual.pretty_name(is_user?) %>
    <b> married on </b>
		 <%= (union.marriage and union.marriage.date) ? union.marriage.date : "date n/a"  %>    
  </div>
  <div class="panel-body">
    <%= form_tag save_added_spouse_path do %>
      <%= render partial: "search" %>
      <br>
      <%= render partial: "event_edit", 
	            locals: { eventname: "Marriage", event: union.marriage, autofocus: true } %>					       
	  <br>
	  <%= submit_tag 'add', class: "btn btn-default" %>
      <%= link_to 'cancel', clear_path, remote:true %>	
    <% end %>	
  </div>	
</div>

app/views/geni/_footer.html.erb
<br>
<br>
<br>
  
<strong> <%= link_to 'Home', root_path, class: "btn btn-info" %> </strong> 
<strong> <%= link_to 'Search', search_path, class: "btn btn-default" %> </strong>

<% if !@compare %>

	<% uid = ( @individual ? @individual.uid : nil ) %>
	
	<div class="btn-group">
	  <%= link_to 'depth <span class="badge">up</span>'.html_safe, 
	            depth_change_path(-1,uid), class: "btn btn-default"  %>
	  <%= link_to '<span class="badge">down</span>'.html_safe, 
	            depth_change_path(1,uid), class: "btn btn-default"  %>
	  <%= link_to 'graph/tree'.html_safe, 
	            vis_change_path( uid ), class: "btn btn-default"  %>   	  
	</div>
	         
	
	
	<% if is_editor? %>
	  <%= link_to 'Edit <span class="badge">'.html_safe + edit? + '</span>'.html_safe, 
	            toggle_edit_path( uid ), class: "btn btn-default"  %> 
	<% end %>
	
    <%= ( link_to 'Compare', compare_path( uid ), class: "btn btn-default" ) if uid %> 
	
	<br> 
	<br> 
	
	<% if is_admin? %>
	  <%= link_to 'New person', new_person_path, class: "btn btn-warning"%> 
	  <%= link_to 'New source', source_edit_path, class: "btn btn-warning"%>   
	  <%= link_to 'Individuals', all_individuals_by_uid_path, class: "btn btn-warning" %> 
	  <%= link_to 'Marriages', all_unions_by_uid_path, class: "btn btn-warning" %>   
	  <%= link_to 'Sources', sources_path, class: "btn btn-warning" %>  
	  <%= link_to 'Import', import_path, class: "btn btn-warning" %> 
	  <%= link_to 'Users', users_path, class: "btn btn-warning" %>  
	<% end %>
	<br>

 <% end %>

app/views/geni/_marriage_new.html.erb
<div class="panel panel-danger">
  <div class="panel-heading">
    <b>Create new (<%= link_to 'existing', marriage_existing_path( individual.uid ), class: 'editlink', remote: true %>)
        person as spouse for </b>
    <%= individual.pretty_name(is_user?) %> 
		  
  </div>
  <div class="panel-body">
    <%= form_tag save_marriage_new_path do %>
  
	  <div class="row">
        <div class="col-xs-4">
          <%= label_tag :given,"Given" %>
          <%= text_field_tag :given, '',
                             class: "form-control input-sm", autofocus: true %>
        </div>
        <div class="col-xs-6">
          <%= label_tag :surname, "Surname" %>
          <%= text_field_tag :surname, '' ,
                             class: "form-control input-sm" %>
        </div>
        <div class="col-xs-2">
          <%= label_tag :sex,"M/F" %>
          <%= text_field_tag :sex, ( individual.male? ? 'F': 'M' ),
                      class: "form-control input-sm" %>
        </div>			
      </div>
	  <div class="row">
        <div class="col-xs-2">
          <%= label_tag :prefix,"Prefix" %>
          <%= text_field_tag :prefix, '', class: "form-control input-sm" %>
        </div>
        <div class="col-xs-2">
          <%= label_tag :prefix,"Nickname" %>
          <%= text_field_tag :nickname, '', class: "form-control input-sm" %>
        </div>
        <div class="col-xs-2">
          <%= label_tag :prefix,"Suffix" %>
          <%= text_field_tag :suffix, '', class: "form-control input-sm" %>
        </div>
        <div class="col-xs-2">
          <%= label_tag :pedigree,"Pedigree" %>
          <%= text_field_tag :pedigree, '', class: "form-control input-sm" %>
        </div>			
      </div>
	  <br>
      <%= render partial: "event_edit", 
		         locals: { eventname: "Birth", event: Event.new, autofocus: false } %>
      <%= render partial: "event_edit", 
	            locals: { eventname: "Marriage", event: Event.new, autofocus: true } %>					 
	  <br>
	  <div class="actions">
	    <%= hidden_field_tag 'tree', individual.tree %>
	    <%= submit_tag 'create', class: "btn btn-default" %>
	    <%= link_to 'cancel', clear_path, remote:true %>
	  </div>        		
    <% end %>	 
  </div>  	
</div>

app/views/geni/_new_child.html.erb
<div class="panel panel-danger">
  <div class="panel-heading">
    <b>Create new 
    (<%= link_to 'existing', add_child_path( individual.uid, union.uid ), class: 'editlink', remote: true %>)
    person as child of </b><%= individual.pretty_name(is_user?) %> <b>and </b>
        <%= ( union.spouse( individual.uid ) ? 
		        union.spouse( individual.uid ).pretty_name(is_user?) : '?' ) %>
  </div>
  <div class="panel-body">
    <%= form_tag create_new_child_path do %>
  
	  <div class="row">
        <div class="col-xs-4">
          <%= label_tag :given,"Given" %>
          <%= text_field_tag :given, '',
                             class: "form-control input-sm", autofocus: true %>
        </div>
        <div class="col-xs-6">
          <%= label_tag :surname, "Surname" %>
          <%= text_field_tag :surname, individual.surname ,
                             class: "form-control input-sm" %>
        </div>
        <div class="col-xs-2">
          <%= label_tag :sex,"M/F" %>
          <%= text_field_tag :sex, @gender, class: "form-control input-sm" %>
        </div>			
      </div>
	  <div class="row">
        <div class="col-xs-2">
          <%= label_tag :prefix,"Prefix" %>
          <%= text_field_tag :prefix, '', class: "form-control input-sm" %>
        </div>
        <div class="col-xs-2">
          <%= label_tag :prefix,"Nickname" %>
          <%= text_field_tag :nickname, '', class: "form-control input-sm" %>
        </div>
        <div class="col-xs-2">
          <%= label_tag :prefix,"Suffix" %>
          <%= text_field_tag :suffix, '', class: "form-control input-sm" %>
        </div>
        <div class="col-xs-2">
          <%= label_tag :pedigree,"Pedigree" %>
          <%= text_field_tag :pedigree, '', class: "form-control input-sm" %>
        </div>			
      </div>
	  <br>
      <%= render partial: "event_edit", 
		         locals: { eventname: "Birth", event: Event.new, autofocus: false } %>
	  <br>
	  <div class="actions">
        <%= hidden_field_tag 'n_uuid', union.uid if union %>
        <%= hidden_field_tag 'tree', individual.tree %>
        INDIVIDUAL <%= individual.uid %>
        UNION <%= union.uid if union %><br>	  
	    <%= submit_tag 'create', class: "btn btn-default" %>
	    <%= link_to 'cancel', clear_path, remote:true %>
	  </div>        		
    <% end %>	 
  </div>  	
</div>

app/views/geni/_new_parent.html.erb
<div class="panel panel-danger">
  <div class="panel-heading">
    <b>Create new person as </b><%= @sex == 'f' ? 'mother' : 'father' %> <b>for </b>
           <%= individual.pretty_name(is_user?) %>
  </div>
  <div class="panel-body">
    <%= form_tag create_new_parent_path do %>
  
	  <div class="row">
        <div class="col-xs-4">
          <%= label_tag :given,"Given" %>
          <%= text_field_tag :given, '',
                             class: "form-control input-sm", autofocus: true %>
        </div>
        <div class="col-xs-6">
          <%= label_tag :surname, "Surname" %>
          <%= text_field_tag :surname, individual.surname ,
                             class: "form-control input-sm" %>
        </div>
        <div class="col-xs-2">
          <%= label_tag :sex,"M/F" %>
          <%= text_field_tag :sex, @sex, class: "form-control input-sm" %>
        </div>			
      </div>
	  <div class="row">
        <div class="col-xs-2">
          <%= label_tag :prefix,"Prefix" %>
          <%= text_field_tag :prefix, @individual.prefix, class: "form-control input-sm" %>
        </div>
        <div class="col-xs-2">
          <%= label_tag :prefix,"Nickname" %>
          <%= text_field_tag :nickname, @individual.nickname, class: "form-control input-sm" %>
        </div>
        <div class="col-xs-2">
          <%= label_tag :prefix,"Suffix" %>
          <%= text_field_tag :suffix, @individual.suffix, class: "form-control input-sm" %>
        </div>
        <div class="col-xs-2">
          <%= label_tag :pedigree,"Pedigree" %>
          <%= text_field_tag :pedigree, @individual.pedigree, class: "form-control input-sm" %>
        </div>			
      </div>
	  <br>
      <%= render partial: "event_edit", 
		         locals: { eventname: "Birth", event: Event.new, autofocus: false } %>
      <%= render partial: "event_edit", 
	           locals: { eventname: "Marriage", event: ( union ? union.marriage : Event.new), autofocus: true } %>		  
	  <br>

	  <div class="actions">
	    <%= hidden_field_tag 'n_uuid', union.uid if union %>
	    <%= hidden_field_tag 'tree', individual.tree %>
	    <%= submit_tag 'create', class: "btn btn-default" %>
	    <%= link_to 'cancel', clear_path, remote:true %>
	  </div>        		
    <% end %>	 
  </div>  	
</div>	  
	  

app/views/geni/_source_edit.html.erb
<div class="panel panel-danger">
  <div class="panel-heading">

	<b>Editing source</b> 
  </div>
  <div class="panel-body">
	<%= form_tag source_save_path( source.id ) do  %>

	  <div class="row">
        <div class="col-xs-4">
          <%= label_tag :title,"Title" %>
          <%= text_field_tag :title, source.title,
                             class: "form-control input-sm", autofocus: true %>
        </div>
      </div>	

	  <div class="row">
	    <div class="col-xs-12">
		  <%= label_tag :content, "Content" %>
          <%= text_area_tag :content,  source.content, cols: 32, class: "form-control" %>
        </div>	  
	  </div>
	  <br>
	  <div class="actions">
	    <%= submit_tag 'save', class: "btn btn-default" %>
	    <%= link_to 'cancel', clear_path, remote:true %>
	  </div>
	  
	<% end %> 
  </div> 
</div>

app/views/geni/_union_edit.html.erb
<div class="panel panel-danger">
  <div class="panel-heading">
	<b>Editing marriage of </b>
	  <% if union.wife %>
		<%= union.wife.pretty_name(is_user?) %>&nbsp;
		<%= '('+union.wife.birth.date+')' if ( union.wife.birth and union.wife.birth.date ) %>
	  <% else %>
	   <%= sex_symbol( 'f' )  %> 
	  <% end %> 
	<br><b>to</b>
	<% if union.husband %>
	  <%= union.husband.pretty_name(is_user?) %>&nbsp;
	      <%= '(' + union.husband.birth.date + ')' if ( union.husband.birth and union.husband.birth.date ) %>
	<% else %>
	   <%= sex_symbol( 'm' )  %> 
    <% end %>	
  </div>
  <div class="panel-body">
	<%= form_tag union_save_path( individual.uid, union.uid ) do  %>

      <%= render partial: "event_edit", 
		         locals: { eventname: "Marriage", event: union.marriage, autofocus: true } %>
      <%= render partial: "event_edit", 
		         locals: { eventname: "Divorce", event: union.divorce, autofocus: false } %>				 
	  <br>
	  
	  <div class="row">
	    <div class="col-xs-12">
		  <%= label_tag :note, "Notes" %>
          <%= text_area_tag :note, union.note, cols: 32, class: "form-control" %>
        </div>	  
	  </div>
	  <br>
	  
	  <div class="actions">
	    <small> Last edit by <%= union.user.username if union.user %> 
		   at <%= union.updated_at.strftime("%H:%M on %-d %b %Y") if union.updated_at %> 
	       &nbsp; &nbsp; &nbsp;</small><br>
	    <%= submit_tag 'save', class: "btn btn-default" %>
	    <%= link_to 'cancel', clear_path, remote:true %>
	  </div>	
	  
	<% end %>  
  </div>
</div>

app/views/geni/clear.js.erb
$('#geni-editcontainer').html("");

app/views/geni/surnames.html.erb
<h1>Last names...</h1>

<div id="surnames">
  <% @surnames.each_with_index do |surname,index| %>
    <% if surname.length > 0 %> 
      <%= link_to( surname, names_for_surname_path( surname: surname ) ) %>
      <%= '|' if index < @surnames.count-1 %>
    <% end %> 
  <% end %>
</div>


<%= render partial: "footer" %>