config/routes.rb
Rails.application.routes.draw do


  # these are the actions related to authentication
  get "_who_are_u" => "authenticate#who_are_u", as: 'who_are_u'
  post "_prove_it" => "authenticate#prove_it", as: 'prove_it'
  post "_about_urself" => "authenticate#about_urself", as: 'about_urself'
  get "_from_mail/(:user_token)" => "authenticate#from_mail", as: 'from_mail'
  post "_ur_secrets" => "authenticate#ur_secrets", as: "ur_secrets"
  get "_reset_mail" => "authenticate#reset_mail", as: 'reset_mail'
  get "_see_u" => "authenticate#see_u", as: 'see_u'
    
  # these should only be available to administrators...
  scope module: 'admin' do  
  
    # for authentication
    resources :users
    get 'users/:id/role_change/:role' => 'users#role_change', as: 'role_change'
    resources :user_actions
    resources :user_sessions  
    resources :site_maps
    
    # for administration
    resources :events
	resources :sources
	resources :source_refs
    resources :individuals
    get 'all_individuals_by_uid' => 'individuals#all_individuals_by_uid', as: 'all_individuals_by_uid'
    get 'individual_by_uid/:uid' => 'individuals#individual_by_uid', as: 'individual_by_uid'
    resources :unions
    get 'all_unions_by_uid' => 'unions#all_unions_by_uid', as: 'all_unions_by_uid'
    get 'union_by_uid/:uid' => 'unions#union_by_uid', as: 'union_by_uid'
           
  end    

  # resources for the app
  get 'surnames' => 'geni#surnames', as: 'surnames'  
  get 'names_for_surname' => 'geni#names_for_surname', as: 'names_for_surname'     
  get 'names_for_term' => 'geni#names_for_term', as: 'names_for_term' 
  get 'sources_for_term' => 'geni#sources_for_term', as: 'sources_for_term'   
  get 'depth_change/:change/(:uid)' => 'geni#depth_change', as: 'depth_change' 
  get 'toggle_edit/(:uid)' => 'geni#toggle_edit', as: 'toggle_edit' 
  get 'import' => 'geni#import', as: 'import'
  post 'file_upload' => 'geni#file_upload', as: 'file_upload'
  
  get 'edit/:uid' => 'geni#edit', as: 'edit'
  get 'detail/:uid' => 'geni#detail', as: 'detail'
  get 'clear' => 'geni#clear', as: 'clear'  
  get 'union_edit/:uuid/:uid' => 'geni#union_edit', as: 'union_edit'
  post 'save/:uid' => 'geni#save', as: 'save'  
  post 'union_save/:uid/:uuid' => 'geni#union_save', as: 'union_save'  
  
  get 'source_edit/(:sid)' => 'geni#source_edit', as: 'source_edit'
  get 'source_delete/:sid/:uid' => 'geni#source_delete', as: 'source_delete'  
  get 'source_content/:sid' => 'geni#source_content', as: 'source_content'  
  post 'source_save/:sid' => 'geni#source_save', as: 'source_save'    
  
=begin  
  match 'marriage_new/:uid' => 'geni#marriage_new', as: 'marriage_new', via: [:get, :post]
  post 'save_marriage_new/:uid' => 'geni#save_marriage_new', as: 'save_marriage_new'  
  match 'marriage_existing/:uid' => 'geni#marriage_existing', as: 'marriage_existing', via: [:get, :post]
  post 'save_marriage_existing/:uid' => 'geni#save_marriage_existing', as: 'save_marriage_existing'    
  get 'delete_marriage/:uid/:uuid' => 'geni#delete_marriage', as: 'delete_marriage' 
=end

  match 'add_spouse/:uid/:uuid' => 'geni#add_spouse', as: 'add_spouse', via: [:get, :post]  
  match 'new_spouse/:uid/:uuid' => 'geni#new_spouse', as: 'new_spouse', via: [:get, :post]    
  post 'save_added_spouse/:uid/:uuid' => 'geni#save_added_spouse', as: 'save_added_spouse'  
  post 'create_new_spouse/:uid/:uuid' => 'geni#create_new_spouse', as: 'create_new_spouse'   
  get 'remove_spouse/:uid/:uuid/:ruid' => 'geni#remove_spouse', as: 'remove_spouse'  
	
  match 'add_child/:uid/:uuid' => 'geni#add_child', as: 'add_child', via: [:get, :post]  
  match 'new_child/:uid/:uuid' => 'geni#new_child', as: 'new_child', via: [:get, :post]    
  post 'save_added_child/:uid/:uuid' => 'geni#save_added_child', as: 'save_added_child'  
  post 'create_new_child/:uid/:uuid' => 'geni#create_new_child', as: 'create_new_child'    
  get 'remove_child/:uid/:puid' => 'geni#remove_child', as: 'remove_child'  
  
  get 'new_person' => 'geni#new_person', as: 'new_person' 
  post 'create_person' => 'geni#create_person', as: 'create_person' 
  
  get 'remove_parent/:uid/:puid' => 'geni#remove_parent', as: 'remove_parent'
  match 'new_parent/:uid/:sex/(:uuid)' => 'geni#new_parent', as: 'new_parent', via: [:get, :post]    
  match 'create_new_parent/:uid/(:uuid)' => 'geni#create_new_parent', as: 'create_new_parent', via: [:get, :post]  
  
  match 'search' => 'geni#search', as: 'search', via: [:get, :post]
  post 'search_results' => 'geni#search_results', as: 'search_results'  
  
  get 'vis_change/(:uid)' => 'geni#vis_change', as: 'vis_change'
  
  get 'compare/:uid/(:uid1)' => 'geni#compare', as: 'compare'
  get 'link/:uid/:uid1/:link' => 'geni#link', as: 'link'  

  # this has to be the last one or else...
  get ':uid' => 'geni#display', as: 'display'

  root "geni#search", as: "root"
    
end

app/models/union.rb
require 'date'

class UnionValidator < ActiveModel::Validator
  def validate(record)
    if ( record.husband_uid == record.wife_uid and record.husband_uid != nil )
      record.errors[:base] << "can't have same person be husband and wife"
    end
  end
end

class Union < ActiveRecord::Base
  validates_with UnionValidator
  belongs_to :marriage, class_name: "Event", foreign_key: "marriage_id"
  belongs_to :divorce, class_name: "Event", foreign_key: "divorce_id"
  belongs_to :user
   
  def self.new( params = {} )
    if params
      params = params.merge( uid: SecureRandom.uuid )
    else
      params = { uid: SecureRandom.uuid }
    end
    super( params )
  end
    
  before_save do
    self.updated_at = nil
    self.ver = self.ver + 1
  end  
  
  def self.by_uid( uid )
    u = Union.where( uid: uid ).order( ver: :asc ).last
    if u
      udup = u.dup
      udup.updated_at = u.updated_at
      udup 
    else
      nil
    end
  end
  
  def update_divorce( params )
    if self.divorce
      self.divorce = self.divorce.dup
      self.divorce.update_attributes( params )
    else
      self.divorce = Event.new( params )
    end
  end
  
  def update_marriage( params )
    if self.marriage
      self.marriage = self.marriage.dup
      self.marriage.update_attributes( params )
    else
      self.marriage = Event.new( params )
    end
  end
    
  def husband=( h )
    self.husband_uid = h ? h.uid : nil
  end
  
  def husband
    Individual.by_uid( self.husband_uid )
  end
  
  def wife=( h )
    self.wife_uid = h ? h.uid : nil
  end
  
  def wife
    Individual.by_uid( self.wife_uid )
  end
  
  def self.all_by_uid
    #uid_groups = Union.group( :uid )    
    sql = "select uid from unions group by uid;"
    uid_groups = ActiveRecord::Base.connection.execute(sql)        
    arr = []
    uid_groups.each do |u|
      arr << Union.by_uid( u[0] )
    end    
    arr
  end
    
  def children
    # this might pull uids who in the past had this value of parents_uid
    # so need to check in the == statement below
    sql = "select uid from individuals where parents_uid = \"#{self.uid}\" group by uid"
    uid_groups = ActiveRecord::Base.connection.execute(sql)    
    child_arr = []
    uid_groups.each do |u|
      i = Individual.by_uid( u[0] )
      if( i.parents_uid == self.uid )
        child_arr << i
      end
    end 
    child_arr.sort! { |a,b| a.name <=> b.name }
    child_arr.sort! { |a,b| sort_by_birth_date( a, b ) }
    
  end
  
  def spouse( uid )
    if husband_uid == uid
      Individual.by_uid( wife_uid )
    elsif wife_uid == uid
      Individual.by_uid( husband_uid )
    else
      nil
    end
  end
  
  def sources
    srefs = SourceRef.where( union_uid: self.uid ) 
    srcs = []		
    srefs.each { |sref| srcs << Source.where( id: sref.source_id ).first }
    srcs.uniq
  end		
    
  private
  
  def sort_by_birth_date( a, b )
    adate = a.birth ? a.birth.date_as_datetime : ''
    bdate = b.birth ? b.birth.date_as_datetime : ''
    if adate.class == bdate.class
      adate <=> bdate
    elsif adate.class == Date
      -1
    elsif bdate.class == Date
      +1
    else
      0
    end       
  end
  
end

app/controllers/admin/unions_controller.rb
module Admin

	class UnionsController < ApplicationController
	  before_action :set_union, only: [:show, :edit, :update, :destroy]
	  before_action :only_if_admin
	  	  
	  # GET /unions
	  # GET /unions.json
	  def index
	    @unions = Union.all
	  end
	
	  # GET /all_unions_by_uid
	  def all_unions_by_uid
	    @unions = Union.all_by_uid
	    
	    if params[:marriage_sorted] 
	      session[:union_marriage_sort] = !session[:union_marriage_sort] 
	      @unions.sort! { |a,b| 
	          Event.compare_dates( a.marriage, b.marriage, session[:union_marriage_sort] ) } 
	    end
	        
	  end
	  
	  # GET /union_by_uid
	  def union_by_uid
	    @union = Union.by_uid( params[:uid] )
        @sources = @union.sources
	  end  
	  
	  # GET /unions/1
	  # GET /unions/1.json
	  def show
	  end
	
	  # GET /unions/new
	  def new
	    @union = Union.new
	  end
	
	  # GET /unions/1/edit
	  def edit
	  end
	
	  # POST /unions
	  # POST /unions.json
	  def create
	    @union = Union.new(union_params)
	       
	    respond_to do |format|
	      if @union.save       
	        format.html { redirect_to @union, notice: 'Union was successfully created.' }
	        format.json { render :show, status: :created, location: @union }
	      else      
	        format.html { render :new }
	        format.json { render json: @union.errors, status: :unprocessable_entity }
	      end
	    end
	  end
	
	  # PATCH/PUT /unions/1
	  # PATCH/PUT /unions/1.json
	  def update
	    respond_to do |format|
	      if @union.update(union_params)
	        format.html { redirect_to @union, notice: 'Union was successfully updated.' }
	        format.json { render :show, status: :ok, location: @union }
	      else
	        format.html { render :edit }
	        format.json { render json: @union.errors, status: :unprocessable_entity }
	      end
	    end
	  end
	
	  # DELETE /unions/1
	  # DELETE /unions/1.json
	  def destroy
	    @union.destroy
	    respond_to do |format|
	      format.html { redirect_to unions_url, notice: 'Union was successfully destroyed.' }
	      format.json { head :no_content }
	    end
	  end
	
	  private
	    # Use callbacks to share common setup or constraints between actions.
	    def set_union
	      @union = Union.find(params[:id])
	    end
	
	    # Never trust parameters from the scary internet, only allow the white list through.
	    def union_params
	      params.require(:union).permit(:uid, :husband_uid, :wife_uid, :marriage_id, :divorce_id, :tree, :note)
	    end
	end
	
end	

app/views/admin/unions/_form.html.erb
<%= form_for(@union) do |f| %>
  <% if @union.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@union.errors.count, "error") %> prohibited this union from being saved:</h2>

      <ul>
      <% @union.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :husband_uid %><br>
    <%= f.text_field :husband_uid %>
  </div>
  <div class="field">
    <%= f.label :wife_uid %><br>
    <%= f.text_field :wife_uid %>
  </div>
  <div class="field">
    <%= f.label :marriage_id %><br>
    <%= f.number_field :marriage_id %>
  </div>
  <div class="field">
    <%= f.label :divorce_id %><br>
    <%= f.number_field :divorce_id %>
  </div>
  <div class="field">
    <%= f.label :tree %><br>
    <%= f.text_field :tree %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/unions/all_by_uid.html.erb
<h1>Listing unions</h1>

<table>
  <thead>
    <tr>
      <th>Marriages</th>    
      <th><%= link_to 'Date', all_unions_by_uid_path( marriage_sorted: true ) %></th>    
      <th>Husband</th>
      <th>Wife</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unions.each do |union| %>
      <tr>
        <td></td>
        <td><%= link_to( truncate( (union.marriage ? 
        ( union.marriage.date ? union.marriage.date : 'w/o date' ) : 'unknown'), length: 20 ), 
                       union_by_uid_path( union.uid) ) %></td>
        <td><%= union.husband ? 
                   link_to( union.husband.pretty_name(is_user?), 
                            individual_by_uid_path( union.husband.uid) ) : '' %>
        <td><%= union.wife ? 
                   link_to( union.wife.pretty_name(is_user?), 
                            individual_by_uid_path( union.wife.uid) ) : '' %>                            
        <td>&nbsp; &nbsp; <small> -<%= union.id %>- <%= union.uid %></small></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= render partial: "geni/footer" %>

app/views/admin/unions/all_unions_by_uid.html.erb
<h1>Listing unions</h1>

<table class="admin-table">
  <thead>
    <tr>
      <th>Marriages</th>    
      <th><%= link_to 'Date', all_unions_by_uid_path( marriage_sorted: true ) %></th>    
      <th>Husband</th>
      <th>Wife</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unions.each do |union| %>
      <tr>
        <td></td>
        <td><%= link_to( truncate( (union.marriage ? 
        ( union.marriage.date ? union.marriage.date : 'w/o date' ) : 'unknown'), length: 20 ), 
                       union_by_uid_path( union.uid) ) %></td>
        <td><%= union.husband ? 
                   link_to( truncate( union.husband.pretty_name(is_user?), length: 30), 
                            individual_by_uid_path( union.husband.uid) ) : '' %></td>
        <td><%= union.wife ? 
                   link_to( truncate( union.wife.pretty_name(is_user?), length: 30), 
                            individual_by_uid_path( union.wife.uid) ) : '' %>  </td>                          
        <td>&nbsp; &nbsp; <small> <%= union.uid %></small></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= render partial: "geni/footer" %>

app/views/admin/unions/by_uid.html.erb
<table width=100%>
  <tr valign='top'><td width=50%>
  
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Uid:</strong>
	  <%= @union.uid %>
	</p>
	
	<p>
	  <strong>Husband:</strong>
	  <%= link_to( @union.husband.pretty_name(is_user?), 
	               individual_by_uid_path( @union.husband.uid ) ) if @union.husband %>   	
	<p>
	  <strong>Wife:</strong>
	  <%= link_to( @union.wife.pretty_name(is_user?), 
	               individual_by_uid_path( @union.wife.uid ) ) if @union.wife %>  
	</p>
	
	<p>
	  <strong>Children:</strong>
	  <% @union.children.each do |child| %>
	    <%= link_to( child.pretty_name(is_user?), 
	               individual_by_uid_path( child.uid ) ) %>  
	  <% end %>
	</p>
		  
	<p>
	  <strong>Marriage:</strong>
	  <%= @union.marriage ? 
	         link_to( ( @union.marriage.date ? @union.marriage.date : 'w/o date' ), @union.marriage )  : 'n/a'%>
	</p>
	
	<p>
	  <strong>Divorce:</strong>
	  <%= @union.divorced %> &nbsp;
	  <%= @union.divorce ? 
	         link_to( ( @union.divorce.date ? @union.divorce.date : 'w/o date' ), @union.divorce )  : 'n/a'%>
	</p>
	
	<p>
	  <strong>Tree:</strong>
	  <%= @union.tree %>
	</p>
	
	<p>
	  <strong>Gedfile:</strong>
	  <%= @union.gedfile %>
	</p>
	
	<p>
	  <strong>Note:</strong>
      <%= simple_format( @union.note ) %> 
	</p>
  </td><td>
	  <pre style="white-space: pre-wrap">
	  <%= @union.gedraw %>
	  </pre>
  </td></tr>
<table>

<%= render partial: "geni/footer" %>

app/views/admin/unions/edit.html.erb
<h1>Editing union</h1>

<%= render 'form' %>

<%= link_to 'Show', @union %> |
<%= link_to 'Back', unions_path %>

app/views/admin/unions/index.html.erb
<h1>Listing unions</h1>

<table class="admin-table">
  <thead>
    <tr>
      <th>Marriage</th>    
      <th>Husband</th>
      <th>Wife</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unions.each do |union| %>
      <tr>
        <td><%= link_to (union.marriage ? union.marriage.date : 'unknown'), union %></td>
        <td><%= union.husband.name if union.husband %></td>
        <td><%= union.wife.name if union.wife %></td>
        <td><%= link_to 'Edit', edit_union_path(union) %></td>
        <td><%= link_to 'Destroy', union, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>&nbsp; &nbsp; <small> <%= union.id %> <%= union.uid %></small></td>
      </tr> 
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Union', new_union_path %>

app/views/admin/unions/new.html.erb
<h1>New union</h1>

<%= render 'form' %>

<%= link_to 'Back', unions_path %>

app/views/admin/unions/show.html.erb
<table width=100%>
  <tr valign='top'><td width=50%>
  
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Uid:</strong>
	  <%= @union.uid %>
	</p>
	
	<p>
	  <strong>Husband:</strong>
	  <%= @union.husband.name if @union.husband %>      	  
	</p>
	
	<p>
	  <strong>Wife:</strong>
	  <%= @union.wife.name if @union.wife %>
	</p>
	
	<p>
	  <strong>Marriage:</strong>
	  <%= @union.marriage ? link_to( @union.marriage.date, @union.marriage ) : 'n/a'%>
	</p>
	
	<p>
	  <strong>Divorce:</strong>
	  <%= @union.divorce_id %>
	</p>
	
	<p>
	  <strong>Tree:</strong>
	  <%= @union.tree %>
	</p>
	
	<p>
	  <strong>Gedfile:</strong>
	  <%= @union.gedfile %>
	</p>
	
	<p>
	  <strong>Note:</strong>
	  <div style="width:100%">
	    <%= simple_format( @union.note ) %> 
	  </div>
	</p>
  </td><td>
	  <pre>
	  <%= @union.gedraw %>
	  </pre>
  </td></tr>
<table>

<%= link_to 'Edit', edit_union_path(@union) %> |
<%= link_to 'Back', unions_path %>

app/views/admin/unions/union_by_uid.html.erb
<table width=100%>
  <tr valign='top'><td width=50%>
  
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Uid:</strong>
	  <%= @union.uid %>
	</p>
	
	<p>
	  <strong>Husband:</strong>
	  <%= link_to( @union.husband.pretty_name(is_user?), 
	               individual_by_uid_path( @union.husband.uid ) ) if @union.husband %>   
	</p>	               	
	<p>
	  <strong>Wife:</strong>
	  <%= link_to( @union.wife.pretty_name(is_user?), 
	               individual_by_uid_path( @union.wife.uid ) ) if @union.wife %>  
	</p>
	
	<p>
	  <strong>Children:</strong>
	  <% @union.children.each do |child| %>
	    <%= link_to( child.pretty_name(is_user?), 
	               individual_by_uid_path( child.uid ) ) %>  
	  <% end %>
	</p>
		  
	<p>
	  <strong>Marriage:</strong>
	  <%= @union.marriage ? 
	         link_to( ( @union.marriage.date ? @union.marriage.date : 'w/o date' ), @union.marriage )  : 'n/a'%>
	</p>
	
	<p>
	  <strong>Divorce:</strong>
	  <%= @union.divorced %> &nbsp;
	  <%= @union.divorce ? 
	         link_to( ( @union.divorce.date ? @union.divorce.date : 'w/o date' ), @union.divorce )  : 'n/a'%>
	</p>
	
	<p>
	  <strong>Tree:</strong>
	  <%= @union.tree %>
	</p>
	
	<p>
	  <strong>Gedfile:</strong>
	  <%= @union.gedfile %>
	</p>
	
	<p>
	  <strong>Note:</strong>
      <%= simple_format( @union.note ) %> 
	</p>

  </td><td>  
  
	<pre style="white-space: pre-wrap">
	  <%= @union.gedraw %>
	</pre>
	<p>
	  <% if @sources %>
	    <b>Sources:</b>
	    <br>
	    <% @sources.each do |source| %>
	      <%= link_to( source.title, source ) %>  
	      <br>
        <% end %>		  
	  <% end %>
	</p>	
	  	  
  </td></tr>
</table>

<%= render partial: "geni/footer" %>