config/routes.rb
Rails.application.routes.draw do


  # these are the actions related to authentication
  get "_who_are_u" => "authenticate#who_are_u", as: 'who_are_u'
  post "_prove_it" => "authenticate#prove_it", as: 'prove_it'
  post "_about_urself" => "authenticate#about_urself", as: 'about_urself'
  get "_from_mail/(:user_token)" => "authenticate#from_mail", as: 'from_mail'
  post "_ur_secrets" => "authenticate#ur_secrets", as: "ur_secrets"
  get "_reset_mail" => "authenticate#reset_mail", as: 'reset_mail'
  get "_see_u" => "authenticate#see_u", as: 'see_u'
    
  # these should only be available to administrators...
  scope module: 'admin' do  
  
    # for authentication
    resources :users
    get 'users/:id/role_change/:role' => 'users#role_change', as: 'role_change'
    resources :user_actions
    resources :user_sessions  
    resources :site_maps
    
    # for administration
    resources :events
	resources :sources
	resources :source_refs
    resources :individuals
    get 'all_individuals_by_uid' => 'individuals#all_individuals_by_uid', as: 'all_individuals_by_uid'
    get 'individual_by_uid/:uid' => 'individuals#individual_by_uid', as: 'individual_by_uid'
    resources :unions
    get 'all_unions_by_uid' => 'unions#all_unions_by_uid', as: 'all_unions_by_uid'
    get 'union_by_uid/:uid' => 'unions#union_by_uid', as: 'union_by_uid'
           
  end    

  # resources for the app
  get 'surnames' => 'geni#surnames', as: 'surnames'  
  get 'names_for_surname' => 'geni#names_for_surname', as: 'names_for_surname'     
  get 'names_for_term' => 'geni#names_for_term', as: 'names_for_term' 
  get 'sources_for_term' => 'geni#sources_for_term', as: 'sources_for_term'   
  get 'depth_change/:change/(:uid)' => 'geni#depth_change', as: 'depth_change' 
  get 'toggle_edit/(:uid)' => 'geni#toggle_edit', as: 'toggle_edit' 
  get 'import' => 'geni#import', as: 'import'
  post 'file_upload' => 'geni#file_upload', as: 'file_upload'
  
  get 'edit/:uid' => 'geni#edit', as: 'edit'
  get 'detail/:uid' => 'geni#detail', as: 'detail'
  get 'clear' => 'geni#clear', as: 'clear'  
  get 'union_edit/:uuid/:uid' => 'geni#union_edit', as: 'union_edit'
  post 'save/:uid' => 'geni#save', as: 'save'  
  post 'union_save/:uid/:uuid' => 'geni#union_save', as: 'union_save'  
  
  get 'source_edit/(:sid)' => 'geni#source_edit', as: 'source_edit'
  get 'source_delete/:sid/:uid' => 'geni#source_delete', as: 'source_delete'  
  get 'source_content/:sid' => 'geni#source_content', as: 'source_content'  
  post 'source_save/:sid' => 'geni#source_save', as: 'source_save'    
  
=begin  
  match 'marriage_new/:uid' => 'geni#marriage_new', as: 'marriage_new', via: [:get, :post]
  post 'save_marriage_new/:uid' => 'geni#save_marriage_new', as: 'save_marriage_new'  
  match 'marriage_existing/:uid' => 'geni#marriage_existing', as: 'marriage_existing', via: [:get, :post]
  post 'save_marriage_existing/:uid' => 'geni#save_marriage_existing', as: 'save_marriage_existing'    
  get 'delete_marriage/:uid/:uuid' => 'geni#delete_marriage', as: 'delete_marriage' 
=end

  match 'add_spouse/:uid/:uuid' => 'geni#add_spouse', as: 'add_spouse', via: [:get, :post]  
  match 'new_spouse/:uid/:uuid' => 'geni#new_spouse', as: 'new_spouse', via: [:get, :post]    
  post 'save_added_spouse/:uid/:uuid' => 'geni#save_added_spouse', as: 'save_added_spouse'  
  post 'create_new_spouse/:uid/:uuid' => 'geni#create_new_spouse', as: 'create_new_spouse'   
  get 'remove_spouse/:uid/:uuid/:ruid' => 'geni#remove_spouse', as: 'remove_spouse'  
	
  match 'add_child/:uid/:uuid' => 'geni#add_child', as: 'add_child', via: [:get, :post]  
  match 'new_child/:uid/:uuid' => 'geni#new_child', as: 'new_child', via: [:get, :post]    
  post 'save_added_child/:uid/:uuid' => 'geni#save_added_child', as: 'save_added_child'  
  post 'create_new_child/:uid/:uuid' => 'geni#create_new_child', as: 'create_new_child'    
  get 'remove_child/:uid/:puid' => 'geni#remove_child', as: 'remove_child'  
  
  get 'new_person' => 'geni#new_person', as: 'new_person' 
  post 'create_person' => 'geni#create_person', as: 'create_person' 
  
  get 'remove_parent/:uid/:puid' => 'geni#remove_parent', as: 'remove_parent'
  match 'new_parent/:uid/:sex/(:uuid)' => 'geni#new_parent', as: 'new_parent', via: [:get, :post]    
  match 'create_new_parent/:uid/(:uuid)' => 'geni#create_new_parent', as: 'create_new_parent', via: [:get, :post]  
  
  match 'search' => 'geni#search', as: 'search', via: [:get, :post]
  post 'search_results' => 'geni#search_results', as: 'search_results'  
  
  get 'vis_change/(:uid)' => 'geni#vis_change', as: 'vis_change'
  
  get 'compare/:uid/(:uid1)' => 'geni#compare', as: 'compare'
  get 'link/:uid/:uid1/:link' => 'geni#link', as: 'link'  

  # this has to be the last one or else...
  get ':uid' => 'geni#display', as: 'display'

  root "geni#search", as: "root"
    
end

app/models/user.rb
require 'securerandom'

  class User < ZiteActiveRecord
  
    validates :username, presence: true, uniqueness: { scope: :site }
    validates :email, presence: true, uniqueness: { scope: :site }, email: true   
    validates :password, length: { minimum: 3 }
    has_secure_password
    has_many :user_sessions, dependent: :destroy
    
    def self.by_email_or_alternate( email )
      user = User.where( email: email ).take
      if !user 
        user = User.where( alternate_email: email ).take
      end  
      return user
    end
    
    def self.by_email_or_username( claim )
      user = User.where( email: claim ).take
      if !user 
        user = User.where( username: claim ).take
      end  
      return user
    end
	
	def self.by_token( token )
	  User.where( token: token).take
	end
	
	def self.by_id( an_id )
	  User.where( id: an_id ).take
	end
  
    def self.new_unconfirmed( email, username )
      user = User.new( email: email, username: username )
      user.password = user.password_confirmation = SecureRandom.urlsafe_base64(8)
      user.token = SecureRandom.urlsafe_base64(16)
      user.active = 'unconfirmed'    
      user
    end
  
    def suspend_and_save
      self.password = self.password_confirmation = SecureRandom.urlsafe_base64(8)
      self.token = SecureRandom.urlsafe_base64(16)
      self.active = 'suspended'
      self.save
    end
       
    def confirmed?
      ( active == 'confirmed' )
    end
    
    def admin?
      ( role == 'admin')     
    end
    def self.admin_emails
      admins = User.where( role: 'admin' )
      emails = []
      admins.each {|a| emails << a.email }
      emails
    end
    def editor?
      ( role == 'admin' or role == 'editor' )
    end
    def user?
       ( role == 'admin' or role == 'editor' or role == 'user')
    end

    def change_role( new_role )
      if ['admin','user','editor'].include? new_role
        self.update_attribute( :role, new_role )
      end
    end
    
    def confirm
      self.update_attribute( :active, confirmed )
    end    
    
  end
  

app/models/user_action.rb
  class UserAction < ZiteActiveRecord
    PARAMS_CLIP = 63
    belongs_to :user_session
    validates :user_session_id, :presence => true  
    validate :user_session_id_valid

    def self.add_action( session_id, controller, action, p )
    
      user_action = self.new( user_session_id: session_id )  
      user_action.controller = controller
      user_action.action = action
      parameters = p.clone
      parameters.delete(:action)
      parameters.delete(:controller)      
      parameters.delete(:password) if parameters[:password]      
      parameters.delete(:password_confirmation) if parameters[:password_confirmation]            
      parameters.delete(:authenticity_token)
      parameters.delete(:utf8)
      parameters[:filename] = p[:file].original_filename if p[:file]
	  user_action.params = ""
	  parameters.each { |k,v| user_action.params += "#{k}: #{v.to_s}; " }
	  user_action.params = user_action.params[0..PARAMS_CLIP]
      user_action.save
    end    
      
    private
    
    def user_session_id_valid
      if ! UserSession.where( id: user_session_id ).take
        errors.add( :user_session_id, "has to be valid" )
      end
    end
    
  end

app/controllers/admin/users_controller.rb
  
module Admin

	class UsersController < ApplicationController
	
	  before_action :set_user, only: [:show, :edit, :update, :destroy]
	  before_action :only_if_admin
	      
	  # GET /users
	  # GET /users.json
	  def index
	    @users = User.all  
	  end
	
	  # GET /users/1
	  # GET /users/1.json
	  def show
	  end
	
	  # GET /users/new
	  def new
	    @user = User.new
	    @user.alternate_email = nil
	  end
	
	  # GET /users/1/edit
	  def edit
	  end
	
	  def role_change
	    @user = User.by_id( params[:id] )
	    @user.change_role( params[:role] )
	    redirect_to action: :index
	  end
	  
	  # POST /users
	  # POST /users.json
	  def create
	    @user = User.new(user_params)
	
	    respond_to do |format|
	      if @user.save
	        format.html { redirect_to @user, notice: 'User was successfully created.' }
	        format.json { render action: 'show', status: :created, location: @user }
	      else
	        format.html { render action: 'new' }
	        format.json { render json: @user.errors, status: :unprocessable_entity }
	      end
	    end
	  end
	
	  # PATCH/PUT /users/1
	  # PATCH/PUT /users/1.json
	  def update
	    respond_to do |format|
	      if @user.update(user_params)
	        format.html { redirect_to @user, notice: 'User was successfully updated.' }
	        format.json { render :show, status: :ok, location: @union }
	      else
	        format.html { render action: 'edit' }
	        format.json { render json: @user.errors, status: :unprocessable_entity }
	      end
	    end
	  end
	
	  # DELETE /users/1
	  # DELETE /users/1.json
	  def destroy
	    @user.destroy
	    respond_to do |format|
	      format.html { redirect_to users_url }
	      format.json { head :no_content }
	    end
	  end
	  	
	  private
	    # Use callbacks to share common setup or constraints between actions.
	    def set_user
		  begin
	        @user = User.by_id(params[:id])
		  rescue Exception => e 	
		    notice = "error #{e} -#{params[:id]}- -#{ZiteActiveRecord.site?}-"
            sql = "select * from users where id = #{params[:id]}"
			res = ActiveRecord::Base.connection.execute(sql)
			res.each do |r|
			  notice += '/n' + r.to_yaml
			end
		    redirect_to users_url, 
			   notice: notice
		  end
	    end
	
	    # Never trust parameters from the scary internet, only allow the white list through.
	    def user_params
	      params.require(:user).permit(:username, :email, :alternate_email, :password, :password_confirmation, :role, :active)
	    end
	    
	end

end

app/views/admin/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :alternate_email %><br>
    <%= f.text_field :alternate_email %>
  </div>  
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.text_field :role %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.text_field :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/admin/users/index.html.erb
<h1>Listing users</h1>

<table  class="admin-table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Username </th>
      <th>Email</th>
      <th>Role</th>
      <th></th>
      <th></th>            
      <th>Active</th>
      <th>Token</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= link_to user.username, user %></td>
        <td><%= user.email %></td>
        <% ['user','editor','admin'].each do |r| %>
          <td>
            <%= ( user.role == r ) ? r.upcase : link_to( r, role_change_path( user, r) ) %>
          </td>
        <% end %>
        <td><%= user.active %></td>
        <td><%= link_to( user.token, from_mail_path( user.token ) ) if user.token %></td>        
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %> |
<%= link_to 'Back', '/' %>

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/admin/users/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Alternate Email:</strong>
  <%= @user.alternate_email %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<p>
  <strong>Active:</strong>
  <%= @user.active %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<small>
	<h1>Sessions for User <%= @user.username %> </h1>
	
	<% @user.user_sessions.reverse.each do |session| %>
	  <h2> <%= link_to ( session.created_at.to_time.strftime("%m/%d %H:%M:%S") + " - " +  
	                     session.updated_at.to_time.strftime("%m/%d %H:%M:%S") ),
	                     session %> </a></h2>
	  
	  <tiny>
	    <% session.user_actions.reverse.each do |action| %>
	      <%= action.created_at.to_time.strftime("%m/%d %H:%M:%S") %> &nbsp; &nbsp; <%= action.controller %>#<%= action.action %> &nbsp; <%= action.params %><br />
	    <% end %>    
	  </tiny>
	       
	<% end %>
</small>