config/routes.rb
Rails.application.routes.draw do


  # these are the actions related to authentication
  get "_who_are_u" => "authenticate#who_are_u", as: 'who_are_u'
  post "_prove_it" => "authenticate#prove_it", as: 'prove_it'
  post "_about_urself" => "authenticate#about_urself", as: 'about_urself'
  get "_from_mail/(:user_token)" => "authenticate#from_mail", as: 'from_mail'
  post "_ur_secrets" => "authenticate#ur_secrets", as: "ur_secrets"
  get "_reset_mail" => "authenticate#reset_mail", as: 'reset_mail'
  get "_see_u" => "authenticate#see_u", as: 'see_u'
    
  # these should only be available to administrators...
  scope module: 'admin' do  
  
    # for authentication
    resources :users
    get 'users/:id/role_change/:role' => 'users#role_change', as: 'role_change'
    resources :user_actions
    resources :user_sessions  
    resources :site_maps
    
    # for administration
    resources :events
	resources :sources
	resources :source_refs
    resources :individuals
    get 'all_individuals_by_uid' => 'individuals#all_individuals_by_uid', as: 'all_individuals_by_uid'
    get 'individual_by_uid/:uid' => 'individuals#individual_by_uid', as: 'individual_by_uid'
    resources :unions
    get 'all_unions_by_uid' => 'unions#all_unions_by_uid', as: 'all_unions_by_uid'
    get 'union_by_uid/:uid' => 'unions#union_by_uid', as: 'union_by_uid'
           
  end    

  # resources for the app
  get 'surnames' => 'geni#surnames', as: 'surnames'  
  get 'names_for_surname' => 'geni#names_for_surname', as: 'names_for_surname'     
  get 'names_for_term' => 'geni#names_for_term', as: 'names_for_term' 
  get 'sources_for_term' => 'geni#sources_for_term', as: 'sources_for_term'   
  get 'depth_change/:change/(:uid)' => 'geni#depth_change', as: 'depth_change' 
  get 'toggle_edit/(:uid)' => 'geni#toggle_edit', as: 'toggle_edit' 
  get 'import' => 'geni#import', as: 'import'
  post 'file_upload' => 'geni#file_upload', as: 'file_upload'
  
  get 'edit/:uid' => 'geni#edit', as: 'edit'
  get 'detail/:uid' => 'geni#detail', as: 'detail'
  get 'clear' => 'geni#clear', as: 'clear'  
  get 'union_edit/:uuid/:uid' => 'geni#union_edit', as: 'union_edit'
  post 'save/:uid' => 'geni#save', as: 'save'  
  post 'union_save/:uid/:uuid' => 'geni#union_save', as: 'union_save'  
  
  get 'source_edit/(:sid)' => 'geni#source_edit', as: 'source_edit'
  get 'source_delete/:sid/:uid' => 'geni#source_delete', as: 'source_delete'  
  get 'source_content/:sid' => 'geni#source_content', as: 'source_content'  
  post 'source_save/:sid' => 'geni#source_save', as: 'source_save'    
  
=begin  
  match 'marriage_new/:uid' => 'geni#marriage_new', as: 'marriage_new', via: [:get, :post]
  post 'save_marriage_new/:uid' => 'geni#save_marriage_new', as: 'save_marriage_new'  
  match 'marriage_existing/:uid' => 'geni#marriage_existing', as: 'marriage_existing', via: [:get, :post]
  post 'save_marriage_existing/:uid' => 'geni#save_marriage_existing', as: 'save_marriage_existing'    
  get 'delete_marriage/:uid/:uuid' => 'geni#delete_marriage', as: 'delete_marriage' 
=end

  match 'add_spouse/:uid/:uuid' => 'geni#add_spouse', as: 'add_spouse', via: [:get, :post]  
  match 'new_spouse/:uid/:uuid' => 'geni#new_spouse', as: 'new_spouse', via: [:get, :post]    
  post 'save_added_spouse/:uid/:uuid' => 'geni#save_added_spouse', as: 'save_added_spouse'  
  post 'create_new_spouse/:uid/:uuid' => 'geni#create_new_spouse', as: 'create_new_spouse'   
  get 'remove_spouse/:uid/:uuid/:ruid' => 'geni#remove_spouse', as: 'remove_spouse'  
	
  match 'add_child/:uid/:uuid' => 'geni#add_child', as: 'add_child', via: [:get, :post]  
  match 'new_child/:uid/:uuid' => 'geni#new_child', as: 'new_child', via: [:get, :post]    
  post 'save_added_child/:uid/:uuid' => 'geni#save_added_child', as: 'save_added_child'  
  post 'create_new_child/:uid/:uuid' => 'geni#create_new_child', as: 'create_new_child'    
  get 'remove_child/:uid/:puid' => 'geni#remove_child', as: 'remove_child'  
  
  get 'new_person' => 'geni#new_person', as: 'new_person' 
  post 'create_person' => 'geni#create_person', as: 'create_person' 
  
  get 'remove_parent/:uid/:puid' => 'geni#remove_parent', as: 'remove_parent'
  match 'new_parent/:uid/:sex/(:uuid)' => 'geni#new_parent', as: 'new_parent', via: [:get, :post]    
  match 'create_new_parent/:uid/(:uuid)' => 'geni#create_new_parent', as: 'create_new_parent', via: [:get, :post]  
  
  match 'search' => 'geni#search', as: 'search', via: [:get, :post]
  post 'search_results' => 'geni#search_results', as: 'search_results'  
  
  get 'vis_change/(:uid)' => 'geni#vis_change', as: 'vis_change'
  
  get 'compare/:uid/(:uid1)' => 'geni#compare', as: 'compare'
  get 'link/:uid/:uid1/:link' => 'geni#link', as: 'link'  

  # this has to be the last one or else...
  get ':uid' => 'geni#display', as: 'display'

  root "geni#search", as: "root"
    
end

app/models/individual.rb
require 'securerandom'

class IndividualValidator < ActiveModel::Validator
  def validate(record)
    if ( !record.name or record.name == '' ) and 
       ( !record.given or record.given == '' ) and 
       ( !record.surname or record.surname == '' )
      record.name = "//"
      # record.errors[:base] << "Need either name or given name or surname."
    end
    if ( !record.surname or record.surname == '' )
      if record.name =~ /\/(.*)\//
        record.surname = $1.strip
      end
    end
    if ( !record.given or record.given == '' )
      if record.name =~ /(.*)\/.*\//
        record.given = $1.strip
      end
    end    
    
  end
end

class Individual < ActiveRecord::Base
  validates_with IndividualValidator
  belongs_to :birth, class_name: "Event", foreign_key: "birth_id"
  belongs_to :death, class_name: "Event", foreign_key: "death_id"
  belongs_to :user
  
  def self.new( params = {} )
    if params
      params = params.merge( uid: SecureRandom.uuid )
    else
      params = { uid: SecureRandom.uuid }
    end
    super( params )
  end
  
  before_save do
    self.updated_at = nil
    self.ver = self.ver + 1
  end  
  
  def living?
    if self.death
      false
    elsif self.birth and self.birth.date and ( self.birth.date_as_datetime < Date.new(1900,1,1) )
      false
    else
      true
    end
  end
  
  def pretty_name( is_user = false )
     
    if is_user or !self.living?
      self.name.gsub( /\//, '')   
    else
      n = self.name.gsub( /\//, '').upcase
      n.split(' ').collect { |s| s[0] }.join('. ') + '.'
    end
     
  end
  
  def pretty_name_multiline( is_user = false )

    if is_user or !self.living?
      p = self.given ? ( (self.given.capitalize.split(' ')[0] || '' ) +'\n') : ''
      p = p + self.surname.capitalize + '\n' if self.surname and self.surname.length > 0
      p = p + ( (self.birth and self.birth.year) ? self.birth.year : '' ) 
      p = p + ( (self.death and self.death.year) ? '-' + self.death.year : '' )  
    else
      n = self.name.gsub( /\//, '').upcase
      n.split(' ').collect { |s| s[0] }.join('. ') + '.'
    end
	
  end
  
  def pretty_first_name( is_user = false )
     
    if is_user or !self.living?
      self.given || self.pretty_name( is_user ) 
    else
      n = self.name.gsub( /\//, '').upcase
      n.split(' ').collect { |s| s[0] }.join('. ') + '.'
    end
     
  end  
  
  def male?
    sex ? sex.downcase == 'm' : false
  end
  def female?
    sex ? sex.downcase == 'f' : false
  end
  
  def self.by_uid( uid )
    
    if uid
      i = Individual.where( uid: uid ).order( ver: :asc ).last
      if i
        idup = i.dup
        idup.updated_at = i.updated_at
        idup 
      else
        nil
      end
    else
      nil
    end 
  end
    
  def self.all_by_uid
    self.all_by_uid_old
  end  
  
  def self.surnames( term = '' )
    sql = "select surname from individuals where surname like \"#{term}%\" group by surname"
    res = ActiveRecord::Base.connection.execute(sql)
    arr = []
    res.each do |n|
      if n[0]
        arr << n[0]
      end
    end
    arr
  end  

  def self.names_for_surname( surname, is_user)
    self.names_for_surname_old( surname, is_user )
  end

  def self.names_for_term( searchterm, is_user )
    self.names_for_term_old( searchterm, is_user )
  end
  
  def update_death( params )
    if self.death
      self.death = self.death.dup
      self.death.update_attributes( params )
    else
      self.death = Event.new( params )
    end
  end
  
  def update_birth( params )
    if self.birth
      self.birth = self.birth.dup
      self.birth.update_attributes( params )
    else
      self.birth = Event.new( params )
    end
  end  
 
  def unions
    u_arr = unions_old
    u_arr.sort { |a,b| sort_by_marriage_date( a, b ) }
  end
  
  def parents=( u )
    self.parents_uid = u ? u.uid : nil  
  end
  
  def parents
    Union.by_uid( self.parents_uid )
  end
  def father
    u = Union.by_uid( self.parents_uid )
    u ? Individual.by_uid( u.husband_uid ) : nil
  end  
  def mother
    u = Union.by_uid( self.parents_uid )
    u ? Individual.by_uid( u.wife_uid ) : nil
  end   
  def is_my_child?( child )
    if child and child.father and child.father.uid == self.uid 
      true
    elsif child and child.mother and child.mother.uid == self.uid
      true
    else
      false
    end
  end
  
  def self.compare_names( i1, i2, order )
    
    if ( i1.surname and i2.surname and i1.surname == i2.surname ) or
           ( !i2.surname and !i1.surname ) 
        if i1.given and i2.given
          return i1.given.downcase <=> i2.given.downcase
        elsif i1.given
          return -1
        elsif i2.given
          return 1
        else
          return 0
        end
    elsif i1.surname and i2.surname
        return ( order ? i1.surname.downcase <=> i2.surname.downcase : 
                         i2.surname.downcase <=> i1.surname.downcase )
    elsif i1.surname
      return -1
    elsif i2.surname
      return 1
    end #  else is not possible...  if both surnames don't exist, first clause hits
    
  end
 
  def sources
    srefs = SourceRef.where( individual_uid: self.uid ) 
    srcs = []		
    srefs.each { |sref| srcs << Source.where( id: sref.source_id ).first }
    srcs.uniq
  end
   
  #
  #  these should be private, this is for testing
  #
  
  def self.all_by_uid_old  
    #uid_groups = Individual.order( tree: :asc).order( name: :asc ).group( :uid )
    sql = "select uid from individuals group by tree, name, uid order by tree asc, name asc;"
    uid_groups = ActiveRecord::Base.connection.execute(sql)    
    arr = []
    uid_groups.each do |u|
      arr << Individual.by_uid( u[0] )
    end
    arr
  end
  
=begin  
  def self.all_by_uid_new
    sql = "select id from individuals where (uid, ver) in (select uid, max(ver) from individuals group by uid) ;"
    res = ActiveRecord::Base.connection.execute(sql)
    array_of_ids = []
    res.each {|r| array_of_ids << r[0]}
    Individual.find( array_of_ids )
  end 
=end
  
  def unions_old
    uid_groups = Union.where( "husband_uid = ? OR wife_uid = ?", self.uid, self.uid ).group( :uid )
    sql = "select uid from unions where (husband_uid = \"#{self.uid}\" or wife_uid = \"#{self.uid}\") group by uid"
    uid_groups = ActiveRecord::Base.connection.execute(sql)        
    union_arr = []
    uid_groups.each do |u|
      union = Union.by_uid( u[0] )
      if ( union.husband and union.husband.uid == self.uid ) or 
         ( union.wife and union.wife.uid == self.uid )
        union_arr << union
      end
    end
    union_arr
  end

=begin
  def unions_new
    sql = "select id, right(uid,5), ver from unions where (uid, ver) in (select uid, max(ver) from unions where (husband_uid = '#{uid}' or wife_uid = '#{uid}') group by uid);"
    res = ActiveRecord::Base.connection.execute(sql)
    array_of_ids = []
    res.each {|r| array_of_ids << r[0]}
    unions = Union.find( array_of_ids )
    unions.sort {|a,b| Event.compare_dates( a.marriage, b.marriage, true ) }
  end
=end
  
  def self.names_for_surname_old( surname, is_user )
    #uid_groups = Individual.where( surname: surname ).group( :uid ).order( given: :asc )
    sql = "select uid from individuals where surname = '#{surname}' group by uid "
    uid_groups = ActiveRecord::Base.connection.execute(sql)
    arr = []	
    uid_groups.each do |u|
	  indi = Individual.by_uid( u[0] )
	  given = indi.pretty_first_name( is_user )
      arr << { fullname: indi.pretty_name( is_user ), given: given, 
	           uid: indi.uid, birth: ( (indi.birth ? indi.birth.date : '' ) || '' ), ver: indi.ver }
    end
    arr.sort { |a,b| a[:given] <=> b[:given] } 
  end
  
=begin  
  def self.names_for_surname_new( surname, is_user )
    sql = "select id, right(uid,5), ver from individuals where (uid, ver) in (select uid, max(ver) from individuals where surname = '#{surname}' group by uid) order by given, ver ASC;"
    res = ActiveRecord::Base.connection.execute(sql)
    array_of_ids = []
    res.each {|r| array_of_ids << r[0]}
    indis = Individual.find( array_of_ids )
    indis.sort! {|a,b| a.given <=> b.given }
	arr = []
    indis.each do |indi|
      arr << { fullname: indi.pretty_name( is_user ), given: indi.pretty_first_name( is_user ), 
	           uid: indi.ulabel_parents_recursively( seed )id, birth: ( (indi.birth ? indi.birth.date : '' ) || '' ), ver: indi.ver }
 	end
    arr  
  end
=end
    
  def self.names_for_term_old( searchterm, is_user )
    terms = searchterm.split(' ')
    sql = ""
	terms.each_with_index do |term,index|
	  sql = sql + "(surname LIKE '%#{term}%' or given LIKE '%#{term}%')"
	  sql = sql + " and "  if index < terms.count-1
    end

    #uid_groups = Individual.where( sql ).group( :uid ).order( given: :asc )
    sql = "select uid from individuals where " + sql + " group by uid ;"
    uid_groups = ActiveRecord::Base.connection.execute(sql)
    arr = []
	uid_groups.each do |u|	
	  indi = Individual.by_uid( u[0] )
	  if !indi.living? || is_user
        arr << { fullname: indi.pretty_name( is_user ), given: indi.pretty_first_name( is_user ), 
	           ver: indi.ver, tree: indi.tree,
	           uid: indi.uid, birth: ( (indi.birth ? indi.birth.date : '' ) || '' ) }
	  end
    end
    arr.sort { |a,b| a[:given] <=> b[:given] } 
  end  

=begin  
  def self.names_for_term_new( searchterm, is_user )
    terms = searchterm.split(' ')
    search_sql = ""
	terms.each_with_index do |term,index|
	  search_sql = search_sql + "(surname LIKE '%#{term}%' or given LIKE '%#{term}%')"
	  search_sql = search_sql + " and "  if index < terms.count-1
    end
	
	sql = "select id, right(uid,5), ver from individuals where (uid, ver) in (select uid, max(ver) from individuals where (#{search_sql}) group by uid) order by given, ver ASC;"
    res = ActiveRecord::Base.connection.execute(sql)
	array_of_ids = []
    res.each {|r| array_of_ids << r[0]}
    indis = Individual.find( array_of_ids )

app/controllers/admin/individuals_controller.rb
module Admin

	class IndividualsController < ApplicationController
	  before_action :set_individual, only: [:show, :edit, :update, :destroy]
	  before_action :only_if_admin
	  
	  # GET /individuals
	  # GET /individuals.json
	  def index
	    @individuals = Individual.all
	  end
	
	  # GET /individuals/1
	  # GET /individuals/1.json
	  def show
	  end
	
	  # GET /all_individuals_by_uid
	  def all_individuals_by_uid          
	    @individuals = Individual.all_by_uid
	    
	    if params[:name_sorted] 
	      session[:individual_name_sort] = !session[:individual_name_sort]         
	      @individuals.sort! { |a,b| Individual.compare_names( a, b, session[:individual_name_sort] ) }
	      
	    elsif params[:birth_sorted] 
	      session[:individual_birth_sort] = !session[:individual_birth_sort] 
	      @individuals.sort! { |a,b| 
	          Event.compare_dates( a.birth, b.birth, session[:individual_birth_sort] ) } 
	    end
	        
	  end
	  
	  # GET /individual_by_uid
	  def individual_by_uid
	    @individual = Individual.by_uid( params[:uid] )
        @sources = @individual.sources		
	  end
	  
	
	  # GET /individuals/new
	  def new
	    @individual = Individual.new
	  end
	
	  # GET /individuals/1/edit
	  def edit
	  end
	
	  # POST /individuals
	  # POST /individuals.json
	  def create
	    @individual = Individual.new(individual_params)
	
	    respond_to do |format|
	      if @individual.save
	        format.html { redirect_to @individual, notice: 'Individual was successfully created.' }
	        format.json { render :show, status: :created, location: @individual }
	      else
	        format.html { render :new }
	        format.json { render json: @individual.errors, status: :unprocessable_entity }
	      end
	    end
	  end
	
	  # PATCH/PUT /individuals/1
	  # PATCH/PUT /individuals/1.json
	  def update
	    respond_to do |format|
	      if @individual.update(individual_params)
	        format.html { redirect_to @individual, notice: 'Individual was successfully updated.' }
	        format.json { render :show, status: :ok, location: @individual }
	      else
	        format.html { render :edit }
	        format.json { render json: @individual.errors, status: :unprocessable_entity }
	      end
	    end
	  end
	
	  # DELETE /individuals/1
	  # DELETE /individuals/1.json
	  def destroy
	    @individual.destroy
	    respond_to do |format|
	      format.html { redirect_to individuals_url, notice: 'Individual was successfully destroyed.' }
	      format.json { head :no_content }
	    end
	  end
	
	  private
	    # Use callbacks to share common setup or constraints between actions.
	    def set_individual
	      @individual = Individual.find(params[:id])
	    end
	
	    # Never trust parameters from the scary internet, only allow the white list through.
	    def individual_params
	      params.require(:individual).permit(:name, :surname, :given, :nickname, :prefix, :suffix, :sex, :birth_id, :death_id, :uid, :parents_uid, :changed_ged, :pedigree, :tree, :gedfile, :note, :gedraw)
	    end
	end
	
end

app/views/admin/individuals/all_by_uid.html.erb
<h1>Listing individuals</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Parents</th>        
      <th><%= link_to 'Surname', all_individuals_by_uid_path( name_sorted: true ) %></th>    
      <th>Given</th>
      <th><%= link_to 'Birth', all_individuals_by_uid_path( birth_sorted: true ) %></th>
      <th>Death</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @individuals.each do |individual| %>
      <tr>
        <td align='right'><%= sex_symbol( individual.sex ) %></td>
        <td><%= link_to individual.pretty_name(is_user?), individual_by_uid_path( individual.uid) %></td>
        <td>
        <%= individual.parents_uid ? 
	     link_to( marriage_symbol, union_by_uid_path( individual.parents_uid ) ) : '' %>
        </td>
        <td><%= truncate( individual.surname, length:12 ) %></td>
        <td><%= truncate( individual.given, length: 12 ) %></td>
        <td><%= individual.birth ? 
               link_to( truncate( individual.birth.date || individual.birth.location || 'n/a', 
                          length: 12), individual.birth ) : ''%></td>
        <td><%= individual.death ? 
               link_to( truncate( individual.death.date || individual.death.location || 'n/a', 
                          length: 12), individual.death ) : ''%></td>   
        <td>&nbsp; &nbsp; <small> -<%= individual.id %>- <%= individual.uid %></small></td>             
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= render partial: "geni/footer" %>

app/views/admin/individuals/all_individuals_by_uid.html.erb
<h1>Listing individuals</h1>

<table class="admin-table">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Parents</th>        
      <th><%= link_to 'Surname', all_individuals_by_uid_path( name_sorted: true ) %></th>    
      <th>Given</th>
      <th><%= link_to 'Birth', all_individuals_by_uid_path( birth_sorted: true ) %></th>
      <th>Death</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @individuals.each do |individual| %>
      <tr>
        <td align='right'><%= sex_symbol( individual.sex ) %></td>
        <td><%= link_to truncate( individual.pretty_name(is_user?), length: 20 ), 
                     individual_by_uid_path( individual.uid) %></td>
        <td>
        <%= individual.parents_uid ? 
	     link_to( marriage_symbol, union_by_uid_path( individual.parents_uid ) ) : '' %>
        </td>
        <td><%= truncate( individual.surname, length:12 ) %></td>
        <td><%= truncate( individual.given, length: 12 ) %></td>
        <td><%= individual.birth ? 
               link_to( truncate( individual.birth.date || individual.birth.location || 'n/a', 
                          length: 12), individual.birth ) : ''%></td>
        <td><%= individual.death ? 
               link_to( truncate( individual.death.date || individual.death.location || 'n/a', 
                          length: 12), individual.death ) : ''%></td>   
        <td>&nbsp; &nbsp; <small> <%= individual.uid %></small></td>             
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= render partial: "geni/footer" %>

app/views/admin/individuals/edit.html.erb
<h1>Editing individual</h1>

<%= render 'form' %>

<%= link_to 'Show', @individual %> |
<%= link_to 'Back', individuals_path %>

app/views/admin/individuals/index.html.erb
<h1>Listing individuals</h1>

<table class="admin-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Given</th>
      <th>Sex</th>
      <th>Birth</th>
      <th>Death</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @individuals.each do |individual| %>
      <tr>
        <td><%= link_to individual.name, individual %></td>
        <td><%= individual.surname %></td>
        <td><%= individual.given %></td>
        <td><%= individual.sex %></td>
        <td><%= individual.birth.date if individual.birth %></td>
        <td><%= individual.death.date if individual.death %></td>
        <td><%= link_to 'Edit', edit_individual_path(individual) %></td>
        <td><%= link_to 'Destroy', individual, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Individual', new_individual_path %>

app/views/admin/individuals/individual_by_uid.html.erb
<b> <%= link_to 'To tree view', display_path( @individual.uid ) %> </b> <br>

<table width=100%>
  <tr valign='top'><td width=50%>
    
  	<p id="notice"><%= notice %></p>
	
	<p>
	  <b>Name:</b>
	  <%= @individual.pretty_name( is_user? ) %>
	</p>
	
	
	<p>
	  <b>Parents:</b>
	  <%= @individual.parents_uid ? 
	     link_to( marriage_symbol, union_by_uid_path( @individual.parents_uid ) ) : '' %>
	</p>
	
	<p>
	  <b>Unions:</b>
	  <br>
	  <% @individual.unions.each do |union| %>
	    <%= link_to( marriage_symbol, union_by_uid_path( union.uid ) ) %>  
	    <%= link_to( union.spouse(@individual.uid).pretty_name(is_user?), 
	               individual_by_uid_path( union.spouse(@individual.uid).uid ) ) if union.spouse(@individual.uid) %>  
        <br>
	  <% end %>
	</p>
		
	<p>
	  <b>Surname:</b>
	  <%= @individual.surname %>
	</p>
	
	<p>
	  <b>Given:</b>
	  <%= @individual.given %>
	</p>
	
	<p>
	  <b>Nickname:</b>
	  <%= @individual.nickname %>
	</p>
	
	<p>
	  <b>Prefix:</b>
	  <%= @individual.prefix %>
	</p>
	
	<p>
	  <b>Suffix:</b>
	  <%= @individual.suffix %>
	</p>
	
	<p>
	  <b>Sex:</b>
	  <%= sex_symbol( @individual.sex ) %>
	</p>
	
	<p>
	  <b>Birth:</b>
	  <%= @individual.birth ? link_to( @individual.birth.date || 'date n/a', @individual.birth ) : ''%>
	  <%= @individual.birth.location if @individual.birth %>
	</p>
	
	<p>
	  <b>Death:</b>
	  <%= @individual.death ? link_to( @individual.death.date || 'date n/a', @individual.death ) : ''%>
	  <%= @individual.death.location if @individual.death %>
	</p>
	
	<p>
	  <b>Uid:</b>
	  <%= @individual.uid %>
	</p>
	
	<p>
	  <b>Pedigree:</b>
	  <%= @individual.pedigree %>
	</p>
	
	<p>
	  <b>Tree:</b>
	  <%= @individual.tree %>
	</p>
	
	<p>
	  <b>Gedfile:</b>
	  <%= @individual.gedfile %>
	</p>
	
	<p>
	  <b>Note:</b>
	  <%= simple_format( @individual.note ) %>   
	</p>
	
	
  </td><td>  
	<pre style="white-space: pre-wrap">
	  <%= @individual.gedraw %>
	</pre>
	  
	<p>
	  <% if @sources %>
	    <b>Sources:</b>
	    <br>
	    <% @sources.each do |source| %>
	      <%= link_to( source.title, source ) %>  
	      <br>
	    <% end %>
	  <% end %>
	</p>
	
  </td></tr>
</table>

<%= render partial: "geni/footer" %>

app/views/admin/individuals/new.html.erb
<h1>New individual</h1>

<%= render 'form' %>

<%= link_to 'Back', individuals_path %>